language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.5
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:

  # Install development dependencies
  - composer install

  # Install and configure WordPress Coding Standards for PHP Code Sniffer
  - git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git /tmp/WordPress-Coding-Standards
  - ./vendor/bin/phpcs --config-set installed_paths /tmp/WordPress-Coding-Standards

  # Provision WP install and test suite for unit testing
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - find . \( -name '*.php' \) -not -path './vendor/*' -exec php -lf {} \;
  - ./vendor/bin/phpcs --standard=ruleset.xml
  - ./vendor/bin/phpunit
